### ISSUE TITLE
Add color swatch to index on last page.

### ISSUE THREAD

**Issue by acrosman** [acrosman/image2pattern#12]
The last page of patterns with multiple colors is an index of the colors and their DMC threads.  Right now that's just a list of text meant to tie to the colors on the pattern itself for support of #7 (and suffering from weaknesses covered in #10). It would be nice to have a little color box next to each entry in the index. 

Code to generate existing index:
https://github.com/acrosman/image2pattern/blob/0f0aaeda379af0ebec2c9532b51ad4411ded6cec/src/image2pattern.js#L223-L242

**Comment by hiby90hou** [comment]
I will try to do it.

**Comment by hiby90hou** [comment]
I solve part of this question, please see my pull request.

**Comment by acrosman** [comment]
I've updated the font used in this part of the PDF.  Please update #13 to use the character you initially had in mind.
