### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by acrosman** [acrosman/image2pattern#17]
**Summary**
Proper unit tests are needed.

**Is your feature request related to a problem? Please describe.**
Currently there are a few small test scripts that ensure code is run in many cases, but they aren't true unit tests just short cuts.

**Describe the solution you'd like**
Unit tests the ensure each method within each module runs properly to the degree possible (testing of generated files is not reasonable at this point since they change a great deal).

**Comment by cortl** [comment]
I'd like to pick up this issue, any test packages you'd like used or do any work?

**Comment by acrosman** [comment]
Since this is an electron app I was more or less assuming Spectron (https://electronjs.org/spectron) perhaps with Mocha (https://mochajs.org/) for the pure node aspects. I am open to other suggestions but that's where I would start.

**Comment by cortl** [comment]
Program didn't generate a cross stitch pattern on my machine (Windows 10) and I'm getting a lot of warnings and errors in the log.

I added Mocha and did some unit level tests on colorUtils.js and ending up fixing quite a bit of it

**Comment by acrosman** [comment]
Thanks for getting this moving.  I'll take a look at the PR in a few minutes.

If you could post the steps you took to run the app along with the warnings, errors, and any other output into an issue so I could take a look at what's going on I'd appreciate it.
