### ISSUE TITLE
Errors getting caught instead of exposed by test script

### ISSUE THREAD

**Issue by acrosman** [acrosman/image2pattern#20]
**Describe the bug**
The gen-test script can trigger errors like those seen here: https://circleci.com/gh/acrosman/image2pattern/12
But they do not result is a non-zero exit code from the script.

**To Reproduce**
1. Setup a new instance of the project without a valid output directory or subdirectories.
1. `npm run gen-test`
2. Note the output reports file permissions errors.

**Expected behavior**
Errors in test scripts should trigger non-zero response codes. Fixing this should trigger errors in the current code base.

**Comment by joeheyming** [comment]
I'm not seeing any file permission errors.  "npm run gen-test" works fine for me.
I manually ran a docker instance:

docker run --rm -v $PWD:/source -i -t  --entrypoint /bin/bash circleci/node:10.12

Then ran npm install in the container.

I noticed lint was failing.  But in your output above, I don't see any lint failures.

I think there is nothing to do here

**Comment by joeheyming** [comment]
https://github.com/acrosman/image2pattern/pull/26

Lint fixes
