### ISSUE TITLE
Add a bold line every 10 squares

### ISSUE THREAD

**Issue by acrosman** [acrosman/image2pattern#3]
The generated patterns should have a bold line every 10 squares to make counting easier.

**Comment by oktak** [comment]
Let me take this~
Do you mean there would be bold lined squares that enclose 100 small squares inside?

**Comment by acrosman** [comment]
#5 addresses this question using additional squares over the top of the existing grid to add the emphasis. This is a pretty straight forward approach similar to what I had envisioned. But those don't make it across the page jumps and the code to do so is likely to be a bit confusing to maintain.

#9 addresses this question by shifting the squares within the image a pixel so the borders for two squares show and give us the effect we want. This has the advantage of reducing extra elements in the image and ensuring that all boxes remain 10x10.  But that means we need to redo the image size calculation because each 10 rows introduces an off-by-one error since the boxes don't overlap. That image size would ideally be based on the PDF page size and will add complexity to that calculation (which isn't currently correct #2).

So both are helpful but neither works quite right. I'm inclined to with fix #5 by using lines over the top of the grid instead of extra squares. The position of those should be easy to calculate. If there is a solution to the image size calculation that is more straight forward than what I'm thinking than I'd be happy with that approach since it will probably work better with the symbols needed for #7.
